version: '3.7'
services:
        nginx:
                image: nginx
                build: ./nginx-conf
                depends_on:
                        - node-con
                        - api-con
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp 
        db-con:
                image: mysql:5.7
                container_name: db-con
                volumes:
                        - type: volume
                          source: mysql-data
                          target: /var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=password 
                        - MYSQL_DATABASE=bank
        node-con:
                image: node-img
                build: ../bank-update-front
        api-con:
                image: api-img
                build: ../bank-update-back
                depends_on:
                        - db-con
volumes:
        mysql-data:



