version: '3.7'
services:
        nginx:
                build: ./nginx-conf
                depends_on:
                        - node-con
                        - api-con
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp 
        db-con:
                image: mysql:5.7
                container_name: db-con
                volumes:
                        - type: volume
                          source: mysql-data
                          target: /var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS} 
                        - MYSQL_DATABASE=taskmanager_app
        node-con:
                image: node-img
                build: ../taks-manager-front-end
        api-con:
                image: api-img
                build: ../task-manager
                depends_on:
                        - db-con
volumes:
        mysql-data:



